version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /operators/kube-rs-building-cronjob
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /operators/poc-secondary-resource-management
    schedule:
      interval: weekly
