version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /experiments/cronjob-tutorial/kube-rs
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /poc
    schedule:
      interval: weekly
