---
apiVersion: v1
kind: Namespace
metadata:
  name: api-extension
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-extension-multi-kinds
  namespace: api-extension
  labels:
    app: api-extension-multi-kinds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-extension-multi-kinds
  template:
    metadata:
      labels:
        app: api-extension-multi-kinds
    spec:
      serviceAccountName: api-extension-multi-kinds
      containers:
        - image: api-extension-multi-kinds
          imagePullPolicy: Never
          name: api-extension-multi-kinds
          ports:
            - containerPort: 3000
              name: https
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-extension-multi-kinds
  namespace: api-extension
spec:
  ports:
    - name: https
      port: 3000
      protocol: TCP
      targetPort: https
  selector:
    app: api-extension-multi-kinds
  type: ClusterIP
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.primary-all
spec:
  group: primary-all
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: api-extension-multi-kinds
    namespace: api-extension
    port: 3000
  version: v1
  versionPriority: 15
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-extension-multi-kinds
  namespace: api-extension
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-extension-multi-kinds
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-extension-multi-kinds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-extension-multi-kinds
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: api-extension-multi-kinds
    namespace: api-extension
