[package]
name = "api-extension"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", default-features = false, features = ["http1", "tokio"] }
tokio = { version = "1.44.1", features = ["full"] }
