[package]
name = "api-extension"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tower = { version = "0.5.2", default-features = false }
tower-http = { version = "0.6.2", default-features = false, features = [
    "trace",
] }
