---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-testing
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark
  namespace: poc-testing
spec:
  ports:
    - name: https
      port: 3000
      protocol: TCP
      targetPort: https
  selector:
    app: benchmark
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark
  namespace: poc-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmark
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: benchmark
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: benchmark
    namespace: poc-testing
